name: swell
description: This is an non official dart swell api for swell.is 
version: 0.0.1
homepage: https://github.com/NeoGold-Dev/swell.dart

repository: https://github.com/NeoGold-Dev/swell.dart

environment:
  sdk: '>=2.17.6 <3.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  retrofit_generator: '>=4.0.0 <5.0.0' 
  json_serializable: '>4.4.0'
  build_runner: ^2.2.0
dependencies: {crypto: ^3.0.2, logger: ^1.1.0, pretty_dio_logger: ^1.2.0-beta-1, retrofit: ^3.0.1+1}
  
